"""Constants used in the Sample Tracker application."""

# ------------------------------
# Transfer template IDs
# ------------------------------
TRANS_TPL_SAME_TO_SAME = 1
TRANS_TPL_SAME_PLATE = 2
TRANS_TPL_PLATE_MERGE = 23
TRANS_TPL_REBATCH_FOR_TRANSFORM = 25
TRANS_TPL_FRAG_ANALYZER = 26
TRANS_TPL_NGS_QC_PASSING = 27
TRANS_TPL_EXTRACTION_TITIN = 34
TRANS_TPL_PCA_PREPLANNING = 35
TRANS_TPL_PCR_PRIMER_HITPICK = 36

# ------------------------------
# Transfer type IDs
# ------------------------------
TRANS_TPL_CLO_INSERT_HITPICK = 2

TRANS_TYPE_PRIMER_HITPICK_CREATE_SRC = 54
TRANS_TYPE_ADD_PCA_MASTER_MIX = 55
TRANS_TYPE_PCA_THERMOCYCLE = 56
TRANS_TYPE_PCR_PRIMER_HITPICK = 57
TRANS_TYPE_PCA_PCR_THERMOCYCLE = 59
