"""Constants used in the Sample Tracker application."""

# ------------------------------
# Transfer template IDs
# ------------------------------
TRANS_TPL_SAME_TO_SAME = 1
TRANS_TPL_SAME_PLATE = 2
TRANS_TPL_96_TO_384 = 18
TRANS_TPL_PLATE_MERGE = 23
TRANS_TPL_REBATCH_FOR_TRANSFORM = 25
TRANS_TPL_FRAG_ANALYZER = 26
TRANS_TPL_NGS_QC_PASSING = 27
TRANS_TPL_EXTRACTION_TITIN = 34
TRANS_TPL_PCA_PREPLANNING = 35
TRANS_TPL_PCR_PRIMER_HITPICK = 36
TRANS_TPL_NGS_POOLING = 31

# ------------------------------
# Transfer type IDs
# ------------------------------
TRANS_TYPE_CLO_INSERT_HITPICK = 2

TRANS_TYPE_QPIX_PICK_COLONIES = 15
TRANS_TYPE_QPIX_TO_384_WELL = 16

TRANS_TYPE_NGS_HITPICK_INDEXING = 26
TRANS_TYPE_NGS_THERMOCYCLING = 27

TRANS_TYPE_HITPICK_MINIPREP = 39
TRANS_TYPE_HITPICK_SHIP_PLATES = 48
TRANS_TYPE_HITPICK_SHIP_TUBES = 51

TRANS_TYPE_PRIMER_HITPICK_CREATE_SRC = 54
TRANS_TYPE_ADD_PCA_MASTER_MIX = 55
TRANS_TYPE_PCA_THERMOCYCLE = 56
TRANS_TYPE_PCR_PRIMER_HITPICK = 57
TRANS_TYPE_PCA_PCR_ADD_MMIX = 58
TRANS_TYPE_PCA_PCR_THERMOCYCLE = 59
TRANS_TYPE_UPLOAD_QUANT = 60
TRANS_TYPE_POST_PCA_NORM = 61
TRANS_TYPE_PCA_PREPLANNING = 53
TRANS_TYPE_NGS_INDEX_HITPICKING = 26
TRANS_TYPE_NGS_MASTERMIX_ADDITION = 82
TRANS_TYPE_NGS_THERMOCYCLE = 27
